/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package c.tech.pkg3.votacion.vistas;

import Encriptador.EncriptadorContraseña;
import c.tech.pkg3.votacion.Persona;
import c.tech.pkg3.votacion.Rol;
import c.tech.pkg3.votacion.dao.DaoPersona;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author ET36
 */
public class añadirUsuario extends javax.swing.JFrame {

    /**
     * Creates new form registro
     */
    public añadirUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        etiquetaañadirusuario = new javax.swing.JLabel();
        etiquetanombre = new javax.swing.JLabel();
        etiquetaapellido = new javax.swing.JLabel();
        etiquetadni = new javax.swing.JLabel();
        etiquetatelefono = new javax.swing.JLabel();
        etiquetacontraseña = new javax.swing.JLabel();
        camponombre = new javax.swing.JTextField();
        campoapellido = new javax.swing.JTextField();
        campodni = new javax.swing.JTextField();
        campotelefono = new javax.swing.JTextField();
        campocontraseña = new javax.swing.JTextField();
        botoncrearusuario = new javax.swing.JButton();
        RolComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        etiquetaañadirusuario.setText("Añadir usuario");

        etiquetanombre.setText("Nombre");

        etiquetaapellido.setText("Apellido");

        etiquetadni.setText("DNI");

        etiquetatelefono.setText("Telefono");

        etiquetacontraseña.setText("Contraseña");

        campoapellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoapellidoActionPerformed(evt);
            }
        });

        campotelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campotelefonoActionPerformed(evt);
            }
        });

        campocontraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campocontraseñaActionPerformed(evt);
            }
        });

        botoncrearusuario.setText("Crear usuario");
        botoncrearusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoncrearusuarioActionPerformed(evt);
            }
        });

        RolComboBox.setModel(new javax.swing.DefaultComboBoxModel<String>(new String[]{"ADMIN","PERSONA"}));

        jLabel1.setText("Rol");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(272, 272, 272)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botoncrearusuario)
                    .addComponent(etiquetaañadirusuario))
                .addContainerGap(228, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(etiquetaapellido)
                                    .addComponent(etiquetanombre)
                                    .addComponent(etiquetadni)
                                    .addComponent(etiquetatelefono)
                                    .addComponent(etiquetacontraseña))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(camponombre)
                                .addGap(92, 92, 92)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(RolComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(87, 87, 87))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(campocontraseña, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                            .addComponent(campotelefono, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campodni, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoapellido, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(etiquetaañadirusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetanombre)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(camponombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RolComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiquetaapellido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiquetadni)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campodni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiquetatelefono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campotelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiquetacontraseña)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campocontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botoncrearusuario)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campocontraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campocontraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campocontraseñaActionPerformed

    private void campoapellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoapellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoapellidoActionPerformed

    private void campotelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campotelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campotelefonoActionPerformed

    private void botoncrearusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoncrearusuarioActionPerformed
        obtenerPersonaInterfaz();
    }//GEN-LAST:event_botoncrearusuarioActionPerformed

    private void obtenerPersonaInterfaz() {
        String nombre = camponombre.getText();
        String apellido = campoapellido.getText();
        String contraseña = campocontraseña.getText();
        Rol rol = Rol.valueOf(String.valueOf(RolComboBox.getSelectedItem()));
        if (nombre.equalsIgnoreCase("") || apellido.equalsIgnoreCase("") || contraseña.equals("") || campotelefono.getText().equalsIgnoreCase("") || campodni.getText().equalsIgnoreCase("") || String.valueOf(RolComboBox.getSelectedItem()).equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese los Datos de manera Correcta");
            return;
        }
        int telefono = Integer.parseInt(campotelefono.getText());
        int dni = Integer.parseInt(campodni.getText());

        DaoPersona dao = new DaoPersona();
        Persona persona = dao.obtenerPersona(dni);
        if (persona != null) {
            JOptionPane.showMessageDialog(null, "YA ESTA REGISTRADO");
            return;
        }
        String contraseñaHash = new EncriptadorContraseña().encriptarContraseña(contraseña);
        dao.ingresarPersona(new Persona(dni, nombre, apellido, telefono, contraseñaHash, rol));
        JOptionPane.showMessageDialog(null, "persona ingresada correctamente");
        limpiarCampos();
    }

    private void limpiarCampos() {
        camponombre.setText("");
        campoapellido.setText("");
        campocontraseña.setText("");
        campotelefono.setText("");
        campodni.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(añadirUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(añadirUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(añadirUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(añadirUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new añadirUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> RolComboBox;
    private javax.swing.JButton botoncrearusuario;
    private javax.swing.JTextField campoapellido;
    private javax.swing.JTextField campocontraseña;
    private javax.swing.JTextField campodni;
    private javax.swing.JTextField camponombre;
    private javax.swing.JTextField campotelefono;
    private javax.swing.JLabel etiquetaapellido;
    private javax.swing.JLabel etiquetaañadirusuario;
    private javax.swing.JLabel etiquetacontraseña;
    private javax.swing.JLabel etiquetadni;
    private javax.swing.JLabel etiquetanombre;
    private javax.swing.JLabel etiquetatelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
