/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package c.tech.pkg3.votacion.vistas;

import c.tech.pkg3.votacion.Lista;
import c.tech.pkg3.votacion.dao.DaoVotacion;
import javax.swing.JOptionPane;

/**
 *
 * @author ET36
 */
public class añadirLista extends javax.swing.JFrame {

    
    public añadirLista() {
        initComponents();
        camponombrerepresentante.setEnabled(false);
        campoapellidorepresentante.setEnabled(false);
        botoncargarrepresentante.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        etiquetaañadirlista = new javax.swing.JLabel();
        camponombrelista = new javax.swing.JTextField();
        botoncargarnombrelista = new javax.swing.JButton();
        etiquetaingresarrepresentantes = new javax.swing.JLabel();
        camponombrerepresentante = new javax.swing.JTextField();
        campoapellidorepresentante = new javax.swing.JTextField();
        botoncargarrepresentante = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        etiquetaañadirlista.setText("Añadir lista");

        camponombrelista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                camponombrelistaActionPerformed(evt);
            }
        });

        botoncargarnombrelista.setText("Cargar nombre");
        botoncargarnombrelista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoncargarnombrelistaActionPerformed(evt);
            }
        });

        etiquetaingresarrepresentantes.setText("Ingresar representante");

        camponombrerepresentante.setText("Ingrese nombre");

        campoapellidorepresentante.setText("Ingrese apellido");

        botoncargarrepresentante.setText("Cargar representante");
        botoncargarrepresentante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoncargarrepresentanteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(camponombrelista, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etiquetaañadirlista))
                        .addGap(18, 18, 18)
                        .addComponent(botoncargarnombrelista))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(campoapellidorepresentante, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                        .addComponent(camponombrerepresentante, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(137, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(etiquetaingresarrepresentantes)
                        .addGap(235, 235, 235))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(botoncargarrepresentante)
                        .addGap(219, 219, 219))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(etiquetaañadirlista)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(camponombrelista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botoncargarnombrelista))
                .addGap(18, 18, 18)
                .addComponent(etiquetaingresarrepresentantes)
                .addGap(32, 32, 32)
                .addComponent(camponombrerepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(campoapellidorepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botoncargarrepresentante)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botoncargarnombrelistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoncargarnombrelistaActionPerformed
        String campoNombre = camponombrelista.getText();
        if (campoNombre.equals("")){
            JOptionPane.showMessageDialog(null, "ingrese un nombre");
            return;
        }
        DaoVotacion dao = new DaoVotacion();
        Lista lista = dao.obtenerListaPorNombre(campoNombre);
        if(lista != null ){
            JOptionPane.showMessageDialog(null, "La Lista Ya Existe");
            return;
        }
        
        dao.añadirLista(campoNombre);
        JOptionPane.showMessageDialog(null, "Lista Cargada Correctamente");
        
        camponombrelista.setEnabled(false);
        
        camponombrerepresentante.setEnabled(true);
        campoapellidorepresentante.setEnabled(true);
        botoncargarrepresentante.setEnabled(true);
        
    }//GEN-LAST:event_botoncargarnombrelistaActionPerformed

    private void camponombrelistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_camponombrelistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_camponombrelistaActionPerformed

    private void botoncargarrepresentanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoncargarrepresentanteActionPerformed
        String nombre = camponombrerepresentante.getText();
        String apellido = campoapellidorepresentante.getText();
        if (nombre.equals("") || apellido.equals("")){
            JOptionPane.showMessageDialog(null, "ingrese todos los datos");
            return;
        }
        DaoVotacion dao = new DaoVotacion();
        dao.añadirRepresentante(camponombrelista.getText(), nombre, apellido);
        JOptionPane.showMessageDialog(null,"Representante ingresado Correctamente");
    }//GEN-LAST:event_botoncargarrepresentanteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(añadirLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(añadirLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(añadirLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(añadirLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new añadirLista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botoncargarnombrelista;
    private javax.swing.JButton botoncargarrepresentante;
    private javax.swing.JTextField campoapellidorepresentante;
    private javax.swing.JTextField camponombrelista;
    private javax.swing.JTextField camponombrerepresentante;
    private javax.swing.JLabel etiquetaañadirlista;
    private javax.swing.JLabel etiquetaingresarrepresentantes;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
