/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package c.tech.pkg3.votacion.vistas;

import c.tech.pkg3.votacion.Lista;
import c.tech.pkg3.votacion.dao.DaoVotacion;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ET36
 */
public class AñadirVotacion extends javax.swing.JFrame {
private List<Lista> listas;
private String nombreVotacion = "";
    public AñadirVotacion() {
        initComponents();
        
        tabladelistasinterna.setEnabled(false);
        botonañadirlistas.setEnabled(false);
         
        

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        etiquetaañadirvotacion = new javax.swing.JLabel();
        tabladelistas = new javax.swing.JScrollPane();
        tabladelistasinterna = new javax.swing.JTable();
        botonañadirlistas = new javax.swing.JButton();
        camponombrevotacion = new javax.swing.JTextField();
        botonAñadirvotacion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoAñoVotacion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        etiquetaañadirvotacion.setText("Añadir votacion");

        DefaultTableModel modelo =  new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false
                return column == 2;
            }
        };

        String columnas[] = {"Id","Nombre"};
        modelo.setColumnIdentifiers(columnas);
        tabladelistasinterna.setModel(modelo);
        tabladelistas.setViewportView(tabladelistasinterna);

        botonañadirlistas.setText("Añadir listas");
        botonañadirlistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonañadirlistasActionPerformed(evt);
            }
        });

        botonAñadirvotacion.setText("Añadir Votacion");
        botonAñadirvotacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAñadirvotacionActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre de la votacion");

        jLabel2.setText("Año de la votacion");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabladelistas, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonAñadirvotacion)
                        .addGap(43, 43, 43))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(campoAñoVotacion, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(325, 325, 325)
                                .addComponent(etiquetaañadirvotacion))
                            .addComponent(jLabel1)
                            .addComponent(camponombrevotacion, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonañadirlistas)
                .addGap(67, 67, 67))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(etiquetaañadirvotacion)
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(camponombrevotacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAñadirvotacion)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoAñoVotacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabladelistas, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonañadirlistas)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonañadirlistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonañadirlistasActionPerformed
         int indices [] = tabladelistasinterna.getSelectedRows();
        for(int i = 0;i<indices.length;i++){          
            System.out.println("i " + indices[i]);
            Integer id = (Integer) (tabladelistasinterna.getValueAt(indices[i],0));           
            DaoVotacion dao = new DaoVotacion();
            System.out.println(id);
            dao.añadirListasAVotacion(nombreVotacion, id);                        
        }
        JOptionPane.showMessageDialog(null, "Listas cargadas en la votacion");
        botonañadirlistas.setEnabled(false);
    }//GEN-LAST:event_botonañadirlistasActionPerformed

    private void botonAñadirvotacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAñadirvotacionActionPerformed
         nombreVotacion = camponombrevotacion.getText();
        if (nombreVotacion.equals("") || campoAñoVotacion.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "ingrese todos los datos");
            return;
        }
        int año = Integer.parseInt(campoAñoVotacion.getText());
        DaoVotacion dao = new DaoVotacion();  
       dao.añadirVotacion(año, nombreVotacion);

        tabladelistasinterna.setEnabled(true);
        botonañadirlistas.setEnabled(true);
        camponombrevotacion.setEnabled(false);
        campoAñoVotacion.setEnabled(false);
        botonAñadirvotacion.setEnabled(false);

         listas = dao.obtenerListas();
        DefaultTableModel modelo = (DefaultTableModel) tabladelistasinterna.getModel();
        for (Lista lista : listas) {
           
         Vector<Object> vector = new Vector<>();

            vector.add(lista.getIdLista());
            vector.add(lista.getNombre());
            modelo.addRow(vector);
        }
        
        
      
    }//GEN-LAST:event_botonAñadirvotacionActionPerformed

    /**
         * @param args the command line arguments
         */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AñadirVotacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AñadirVotacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AñadirVotacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AñadirVotacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AñadirVotacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAñadirvotacion;
    private javax.swing.JButton botonañadirlistas;
    private javax.swing.JTextField campoAñoVotacion;
    private javax.swing.JTextField camponombrevotacion;
    private javax.swing.JLabel etiquetaañadirvotacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane tabladelistas;
    private javax.swing.JTable tabladelistasinterna;
    // End of variables declaration//GEN-END:variables

  
    
    
}
