/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package c.tech.pkg3.votacion.vistas;

import c.tech.pkg3.votacion.Lista;
import c.tech.pkg3.votacion.Persona;
import c.tech.pkg3.votacion.Votacion;
import c.tech.pkg3.votacion.dao.DaoVotacion;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author ET36
 */
public class generarVoto extends javax.swing.JFrame {

    private List<Votacion> votaciones;
    private Votacion votacionElegida ;
    private Lista listaElegida;
    private Persona persona;

    public generarVoto(Persona persona) {
        DaoVotacion dao = new DaoVotacion();
        votaciones = dao.obtenerVotaciones();       
        initComponents();
        this.persona = persona;

        DefaultComboBoxModel modelo = (DefaultComboBoxModel) listavotacion.getModel();

        for (Votacion votacion : votaciones) {      
            if(votacion.getActiva() == 0) { // 0 quiere decir que esta activa
            String dato = votacion.getDescripcion() + " " + votacion.getAño();            
            modelo.addElement(dato);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        etiquetagenerarvoto = new javax.swing.JLabel();
        listavotacion = new javax.swing.JComboBox<>();
        etiquetaseleccionarvotacion = new javax.swing.JLabel();
        etiquetaseleccionarlista = new javax.swing.JLabel();
        listadelistas = new javax.swing.JComboBox<>();
        botonvotar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        etiquetagenerarvoto.setText("Generar voto");

        listavotacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));
        listavotacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listavotacionMouseClicked(evt);
            }
        });
        listavotacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listavotacionActionPerformed(evt);
            }
        });

        etiquetaseleccionarvotacion.setText("Seleccionar votacion");

        etiquetaseleccionarlista.setText("Seleccionar lista");

        listadelistas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));
        listadelistas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                listadelistasMouseReleased(evt);
            }
        });
        listadelistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listadelistasActionPerformed(evt);
            }
        });

        botonvotar.setText("Votar");
        botonvotar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonvotarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(listavotacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etiquetaseleccionarvotacion)
                            .addComponent(etiquetaseleccionarlista)
                            .addComponent(listadelistas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonvotar)
                            .addComponent(etiquetagenerarvoto))))
                .addContainerGap(267, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(etiquetagenerarvoto)
                .addGap(67, 67, 67)
                .addComponent(etiquetaseleccionarvotacion)
                .addGap(18, 18, 18)
                .addComponent(listavotacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(etiquetaseleccionarlista)
                .addGap(18, 18, 18)
                .addComponent(listadelistas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(botonvotar)
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listavotacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listavotacionActionPerformed
  
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) listadelistas.getModel();
        List<Lista> listas = votaciones.get(listavotacion.getSelectedIndex()).getListas();
        votacionElegida = votaciones.get(listavotacion.getSelectedIndex());
        modelo.removeAllElements();
        for (Lista lista : listas) {                     
            modelo.addElement(lista.getNombre());
        }
        

    }//GEN-LAST:event_listavotacionActionPerformed

    private void botonvotarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonvotarActionPerformed
      
        DaoVotacion dao = new DaoVotacion();
        if (dao.personaVoto(persona.getDni(), votacionElegida.getId())) {  // SI ES TRUE, LA PERSONA YA VOTO
            JOptionPane.showMessageDialog(null, "Ya voto");
            return;
        }
        dao.votar(persona.getDni(), votacionElegida.getId(), listaElegida.getIdLista());
        JOptionPane.showMessageDialog(null, "Voto cargado exitosamente");
    }//GEN-LAST:event_botonvotarActionPerformed

    private void listavotacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listavotacionMouseClicked

    }//GEN-LAST:event_listavotacionMouseClicked

    private void listadelistasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listadelistasMouseReleased
        // TODOadd your handling code here:
    }//GEN-LAST:event_listadelistasMouseReleased

    private void listadelistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listadelistasActionPerformed
       if(votacionElegida != null && listadelistas.getSelectedIndex() != -1){
        listaElegida = votacionElegida.getListas().get(listadelistas.getSelectedIndex());
       }
    }//GEN-LAST:event_listadelistasActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonvotar;
    private javax.swing.JLabel etiquetagenerarvoto;
    private javax.swing.JLabel etiquetaseleccionarlista;
    private javax.swing.JLabel etiquetaseleccionarvotacion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> listadelistas;
    private javax.swing.JComboBox<String> listavotacion;
    // End of variables declaration//GEN-END:variables
}
