/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package c.tech.pkg3.votacion.vistas;

import c.tech.pkg3.votacion.Estadisticas;
import c.tech.pkg3.votacion.Lista;
import c.tech.pkg3.votacion.Votacion;
import c.tech.pkg3.votacion.dao.DaoVotacion;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author ET36
 */
public class inicioAdmin extends javax.swing.JFrame {
private List<Votacion> votaciones;
    public inicioAdmin() {
        initComponents();
        DaoVotacion dao = new DaoVotacion();
         votaciones = dao.obtenerVotaciones();
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) listavotacion.getModel();
        for (Votacion votacion : votaciones) {
            String dato = votacion.getDescripcion() + " " + votacion.getAño();
            modelo.addElement(dato);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        etiquetainicio = new javax.swing.JLabel();
        botonusuario = new javax.swing.JButton();
        botonlista = new javax.swing.JButton();
        botonvotacion = new javax.swing.JButton();
        listavotacion = new javax.swing.JComboBox<>();
        etiquetamostrarvotacion = new javax.swing.JLabel();
        botonmostrarvotacion = new javax.swing.JButton();
        botonVerEstadisticas = new javax.swing.JButton();
        botonDesactivarVotacion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        etiquetainicio.setText("Inicio Admin");

        botonusuario.setText("Añadir usuario");
        botonusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonusuarioActionPerformed(evt);
            }
        });

        botonlista.setText("Crear lista");
        botonlista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonlistaActionPerformed(evt);
            }
        });

        botonvotacion.setText("Crear votacion");
        botonvotacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonvotacionActionPerformed(evt);
            }
        });

        listavotacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        listavotacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listavotacionActionPerformed(evt);
            }
        });

        etiquetamostrarvotacion.setText("Votaciones");

        botonmostrarvotacion.setText("Mostrar votacion");
        botonmostrarvotacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonmostrarvotacionActionPerformed(evt);
            }
        });

        botonVerEstadisticas.setText("Ver Estadisticas");
        botonVerEstadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerEstadisticasActionPerformed(evt);
            }
        });

        botonDesactivarVotacion.setText("Desactivar Votacion");
        botonDesactivarVotacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDesactivarVotacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(etiquetainicio)
                .addGap(269, 269, 269))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botonVerEstadisticas, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(botonvotacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonlista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonusuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiquetamostrarvotacion, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(botonmostrarvotacion)
                                .addGap(44, 44, 44)
                                .addComponent(botonDesactivarVotacion))
                            .addComponent(listavotacion, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(233, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(etiquetainicio)
                .addGap(32, 32, 32)
                .addComponent(botonusuario)
                .addGap(18, 18, 18)
                .addComponent(botonlista)
                .addGap(18, 18, 18)
                .addComponent(botonvotacion)
                .addGap(18, 18, 18)
                .addComponent(botonVerEstadisticas)
                .addGap(28, 28, 28)
                .addComponent(etiquetamostrarvotacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(listavotacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonmostrarvotacion)
                    .addComponent(botonDesactivarVotacion))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonusuarioActionPerformed
        añadirUsuario a = new añadirUsuario();
        a.setVisible(true);
    }//GEN-LAST:event_botonusuarioActionPerformed

    private void botonvotacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonvotacionActionPerformed
        AñadirVotacion a = new AñadirVotacion();
        a.setVisible(true);
    }//GEN-LAST:event_botonvotacionActionPerformed

    private void listavotacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listavotacionActionPerformed

    }//GEN-LAST:event_listavotacionActionPerformed

    private void botonlistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonlistaActionPerformed
        añadirLista a = new añadirLista();
        a.setVisible(true);
    }//GEN-LAST:event_botonlistaActionPerformed

    private void botonVerEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerEstadisticasActionPerformed
        verEstadisticas a = new verEstadisticas();
        a.setVisible(true);
    }//GEN-LAST:event_botonVerEstadisticasActionPerformed

    private void botonmostrarvotacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonmostrarvotacionActionPerformed
       int idVotacion = votaciones.get(listavotacion.getSelectedIndex()).getId();        
        verEstadisticas ver = new verEstadisticas(new DaoVotacion().obtenerEstadisticasIdVotacion(idVotacion));
        ver.setVisible(true);
    }//GEN-LAST:event_botonmostrarvotacionActionPerformed

    private void botonDesactivarVotacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDesactivarVotacionActionPerformed
        int idVotacion = votaciones.get(listavotacion.getSelectedIndex()).getId();        
        new DaoVotacion().desactivarVotacion(idVotacion);
        JOptionPane.showMessageDialog(null, "votacion desactivada correctamente");
    }//GEN-LAST:event_botonDesactivarVotacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicioAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicioAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicioAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicioAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicioAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonDesactivarVotacion;
    private javax.swing.JButton botonVerEstadisticas;
    private javax.swing.JButton botonlista;
    private javax.swing.JButton botonmostrarvotacion;
    private javax.swing.JButton botonusuario;
    private javax.swing.JButton botonvotacion;
    private javax.swing.JLabel etiquetainicio;
    private javax.swing.JLabel etiquetamostrarvotacion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> listavotacion;
    // End of variables declaration//GEN-END:variables
}
